# Generated by Django 4.2.2 on 2023-07-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raca', models.CharField(max_length=30, verbose_name='raca')),
                ('data_entrada', models.DateField(max_length=10, verbose_name='data_entrada')),
            ],
            options={
                'ordering': ['data_entrada', 'raca'],
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(max_length=10, verbose_name='data')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producao.criacao', verbose_name='criacao')),
            ],
        ),
    ]
